# mc-execute - example

In [1]:
import numpy as np
from mc_execute import Execute, Entity

In [2]:
## 1. Entity

# A = B = C
A = Entity().tp("1 2 3 -90 0")
B = Entity().tp("1 2 3").rotate("-90 0")
C = Entity().tp(np.array([1.5, 2., 3.5], dtype=np.float64)).rotate(np.array([270., 0.], dtype=np.float32))

marker = Entity()   # same as tp("0. 0. 0.").rotate("0. 0.")
player = Entity().setDimension("overworld").setEyeLevel(1.62)

print(f'[Entity A]   position: {A.position},   rotation: {A.rotation}')
print(f'[Entity B]   position: {B.position},   rotation: {B.rotation}')
print(f'[Entity C]   position: {C.position},   rotation: {C.rotation}')

[Entity A]   position: [1.5 2.  3.5],   rotation: [-90.   0.]
[Entity B]   position: [1.5 2.  3.5],   rotation: [-90.   0.]
[Entity C]   position: [1.5 2.  3.5],   rotation: [-90.   0.]


In [3]:
## 2. Execute Context

P = Entity().tp("1. 2. 3. 0. 0.")
Q = Entity().tp("2. 4. 6. 90. 0.")
R = Entity().tp("3. 6. 9. 180. 0.")

# a1 = a2 (execute as P at @s)
a1 = Execute().as_(P).at()
a2 = Execute(P)
a3 = Execute(a2)    # context copy

# execute as P at Q rotated as R
chicken = Entity(Execute().as_(P).at(Q).rotated(R))
print(chicken.position)

marker.tp("1. 0. 1.")

# execute as A at @s rotated -45. 0.
A.tp("0. 0. 0. 0. 0.").rotate(Execute(A).rotated("-45. 0.").rotations[0])
# execute as B at @s rotated -45. 0. facing ^ ^ ^1 facing ^ ^ ^1
B.tp("0. 0. 0. 0. 0.").rotate(Execute(B).rotated("-45. 0.").facing("^ ^ ^1").facing("^ ^ ^1").rotations[0])

# Same precision error as in-game
print()
print(f"[Entity A]  position: {A.position}, rotation:   {A.rotation}")
print(f"[Entity B]  position: {B.position}, rotation:   {B.rotation}")


[2. 4. 6.]

[Entity A]  position: [0. 0. 0.], rotation:   [-45.   0.]
[Entity B]  position: [0. 0. 0.], rotation:   [-45.005497  -0.      ]


In [4]:
## 3. Context Fork

# execute as [A, B]
b1 = Execute().as_([A, B])

# (execute as [A, B]) at [P, Q, R] rotated as @s
b2 = Execute(b1).at([P, Q, R]).rotated()

# (execute as [A, B]) positioned [[0.,0.,0.], [3.,3.,3.]]
b3 = Execute(b1).positioned(np.array([[0., 0., 0.], [3., 3., 3.]], dtype=np.float64))

print(f'b1.positions:\n{b1.positions}')
print(f'b2.positions:\n{b2.positions}')
print(f'b2.rotations:\n{b2.rotations}')
print(f'b3.positions:\n{b3.positions}')


b1.positions:
[[0. 0. 0.]
 [0. 0. 0.]]
b2.positions:
[[1. 2. 3.]
 [2. 4. 6.]
 [3. 6. 9.]
 [1. 2. 3.]
 [2. 4. 6.]
 [3. 6. 9.]]
b2.rotations:
[[-45.         0.      ]
 [-45.         0.      ]
 [-45.         0.      ]
 [-45.005497  -0.      ]
 [-45.005497  -0.      ]
 [-45.005497  -0.      ]]
b3.positions:
[[0. 0. 0.]
 [3. 3. 3.]
 [0. 0. 0.]
 [3. 3. 3.]]
